---
language: go

go:
  - 1.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

env:
- "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  # Fetch dependencies
  - go get -d ./GoLinkShortener/

script:
  # Build Url Shortener
  - go build -o UrlShortener ./GoLinkShortener/
