FROM gliderlabs/alpine:3.3

WORKDIR /app

ADD GoLinkShortener/GoLinkShortener /app
ADD GoLinkShortener/index.html /app

RUN groupadd -r user && useradd -r -g user user
USER user

EXPOSE 5100:5100
CMD ["/app/GoLinkShortener"]
